theme: jekyll-theme-minima
title: NM Capit's Homepage
description: For daily notes
paginate: 5
paginate_path: "/blog/p:num/"
collections_dir: collections # 选择指定一个目录来将所有合集和posts存储在同一个位置
collections:
  collection01: # 你的collection名称
    output: true 
defaults:
  -
    scope:
      path: ""
      type: "collection01" # a collection in your site, in plural form
    values:
      layout: "default"
